apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base

# Se precisar sobrescrever algum valor espec√≠fico para o ambiente dev
patches:
  - target:
      kind: ConfigMap
      name: api-integration-config
    path: values.yaml
